### ISSUE TITLE
name 'facenet_model' is not defined

### ISSUE THREAD

**Issue by samarrik** [AffectAnalysisGroup/PyAFAR#9]
For some reason, when I'm starting to process the video using GUI, the following error message is being sent to me multiple times:

name 'facenet_model' is not defined

**Comment by bmaneesh** [comment]
Hi, we updated PyAFAR with a new release. 

We have also disabled using the FaceNet model since v3.0.0 and you should not be getting the 'facenet_model' is not defined error if you are using v3 or beyond (we recommend our latest release). Please reopen the issue if you still encounter the problem when using the latest release.
